FROM pihole/pihole:latest

ENV TZ=Asia/Kolkata

# Optional: preload extra blocklists
# COPY adlists.list /etc/pihole/adlists.list

# Optional: custom dnsmasq configs
# COPY 02-custom.conf /etc/dnsmasq.d/

EXPOSE 53/tcp 53/udp 80
